### ISSUE TITLE
Add ability to specify the channel while uploading

### ISSUE THREAD

**Issue by hackmonker** [divyam234/teldrive-upload#7]
Right now the upload occurs only in the default channel. Even though multiple channels is possible , upload to any channel is not. Hope that is also added to the uploader so we can specify which channel the folder/file is being uploaded to.

**Comment by xd003** [comment]
+1 for this request
To utilise multiple channels for teldrive, currently we have to only upload it though the UI after changing default channel which is not really convenient

**Comment by hackmonker** [comment]
Support for channel was added in this commit 0593f56068909dd18889f61d15b3817fba77fad3
